### PR TITLE
giffffff!!!!

### PR DESCRIPTION
**Pull request by sssionggg**
we have such a nice gif, we should definitely use it!!!

we still need to update the link once this PR is merged(it will, right????).

example page: https://github.com/siong1987/HackAColaSign/tree/GIFFFFFFFFF

### CODE REVIEW

**Comment by zadr** [comment]
🙌🙌🙌

It looks like GitHub supports [relative links](https://help.github.com/articles/relative-links-in-readmes/) for this, so referencing it as `Assets/hackacola.gif` should work?

**Comment by keyosk** [comment]
Yep, please use a relative link, for instance, in our README I added a bunch of relative links, ie:

```
[EverythingOn](./EverythingOn)
```

**Comment by sssionggg** [comment]
@keyosk @zadr will do!

**Comment by sssionggg** [comment]
done :)

@keyosk you are right.  so many relative examples in the README and i didn't see them :(

**Comment by keyosk** [comment]
Thanks @siong1987 !

**Pull request merged**
